services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:slyLQCV)(98cvtp@formulating.c88yhjcbemef.eu-north-1.rds.amazonaws.com:5432/formulating
    entrypoint: [ "/app/start.sh" ]
    command: [ "/app/main" ]