// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: ingredient.sql

package db

import (
	"context"
	"database/sql"
)

const createIngredient = `-- name: CreateIngredient :one
INSERT INTO ingredients (
                        name,
                        user_id
) VALUES (
          $1, $2
         ) RETURNING id, name, user_id, created_at
`

type CreateIngredientParams struct {
	Name   string        `json:"name"`
	UserID sql.NullInt64 `json:"userID"`
}

func (q *Queries) CreateIngredient(ctx context.Context, arg CreateIngredientParams) (Ingredient, error) {
	row := q.db.QueryRowContext(ctx, createIngredient, arg.Name, arg.UserID)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteIngredient = `-- name: DeleteIngredient :exec
DELETE FROM ingredients
WHERE id = $1
`

func (q *Queries) DeleteIngredient(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteIngredient, id)
	return err
}

const deleteIngredientsByUserId = `-- name: DeleteIngredientsByUserId :exec
DELETE FROM ingredients
WHERE user_id = $1
`

func (q *Queries) DeleteIngredientsByUserId(ctx context.Context, userID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, deleteIngredientsByUserId, userID)
	return err
}

const getIngredient = `-- name: GetIngredient :one
SELECT id, name, user_id, created_at FROM ingredients
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetIngredient(ctx context.Context, id int64) (Ingredient, error) {
	row := q.db.QueryRowContext(ctx, getIngredient, id)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const listIngredients = `-- name: ListIngredients :many
SELECT id, name, user_id, created_at FROM ingredients
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListIngredientsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListIngredients(ctx context.Context, arg ListIngredientsParams) ([]Ingredient, error) {
	rows, err := q.db.QueryContext(ctx, listIngredients, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ingredient
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIngredientsByUserId = `-- name: ListIngredientsByUserId :many
SELECT id, name, user_id, created_at FROM ingredients
    WHERE user_id = $1
    ORDER BY id
    LIMIT $2
    OFFSET $3
`

type ListIngredientsByUserIdParams struct {
	UserID sql.NullInt64 `json:"userID"`
	Limit  int32         `json:"limit"`
	Offset int32         `json:"offset"`
}

func (q *Queries) ListIngredientsByUserId(ctx context.Context, arg ListIngredientsByUserIdParams) ([]Ingredient, error) {
	rows, err := q.db.QueryContext(ctx, listIngredientsByUserId, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ingredient
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIngredientName = `-- name: UpdateIngredientName :one
UPDATE ingredients
SET name = $2
WHERE id = $1
RETURNING id, name, user_id, created_at
`

type UpdateIngredientNameParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpdateIngredientName(ctx context.Context, arg UpdateIngredientNameParams) (Ingredient, error) {
	row := q.db.QueryRowContext(ctx, updateIngredientName, arg.ID, arg.Name)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}
