// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CreateBatch(ctx context.Context, arg CreateBatchParams) (Batch, error)
	CreateBatchItem(ctx context.Context, arg CreateBatchItemParams) (BatchItem, error)
	CreateCurrency(ctx context.Context, name string) (Currency, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreateFormula(ctx context.Context, arg CreateFormulaParams) (Formula, error)
	CreateFormulaIngredient(ctx context.Context, arg CreateFormulaIngredientParams) (FormulaIngredient, error)
	CreateIngredient(ctx context.Context, arg CreateIngredientParams) (Ingredient, error)
	CreateIngredientFunction(ctx context.Context, arg CreateIngredientFunctionParams) (IngredientFunction, error)
	CreateIngredientTag(ctx context.Context, arg CreateIngredientTagParams) (IngredientTag, error)
	CreateIngredientTagMap(ctx context.Context, arg CreateIngredientTagMapParams) (IngredientTagMap, error)
	CreateInventoryItem(ctx context.Context, arg CreateInventoryItemParams) (InventoryItem, error)
	CreatePhase(ctx context.Context, arg CreatePhaseParams) (Phase, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateStripeEntry(ctx context.Context, arg CreateStripeEntryParams) (Stripe, error)
	CreateStripePlan(ctx context.Context, arg CreateStripePlanParams) (StripePlan, error)
	CreateTester(ctx context.Context, email string) (Tester, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVersion(ctx context.Context, number sql.NullFloat64) (Version, error)
	DeleteBatch(ctx context.Context, id int64) error
	DeleteBatchItem(ctx context.Context, id int64) error
	DeleteCurrency(ctx context.Context, id int64) error
	DeleteEntry(ctx context.Context, id int64) error
	DeleteFormula(ctx context.Context, id int64) error
	DeleteFormulaIngredient(ctx context.Context, id int64) error
	DeleteFormulaIngredientsNotInUpdate(ctx context.Context, arg DeleteFormulaIngredientsNotInUpdateParams) error
	DeleteIngredient(ctx context.Context, id int64) error
	DeleteIngredientFunction(ctx context.Context, id int64) error
	DeleteIngredientTag(ctx context.Context, id int64) error
	DeleteIngredientTagMap(ctx context.Context, id int64) error
	DeleteIngredientTagMapByIngredientId(ctx context.Context, ingredientID int64) error
	DeleteIngredientsByUserId(ctx context.Context, userID int64) error
	DeleteInventoryItem(ctx context.Context, id int64) error
	DeletePhase(ctx context.Context, id int64) error
	DeleteTransfer(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetBatch(ctx context.Context, id int64) (Batch, error)
	GetBatchItem(ctx context.Context, id int64) (BatchItem, error)
	GetCurrency(ctx context.Context, id int64) (Currency, error)
	GetEntryByUserId(ctx context.Context, userID sql.NullInt64) (Entry, error)
	GetFormula(ctx context.Context, id int64) (Formula, error)
	GetFormulaIngredient(ctx context.Context, id int64) (FormulaIngredient, error)
	GetFullFormula(ctx context.Context, id int64) ([]GetFullFormulaRow, error)
	GetIngredient(ctx context.Context, id int64) (Ingredient, error)
	GetIngredientCount(ctx context.Context, userID int64) (int64, error)
	GetIngredientFunction(ctx context.Context, id int64) (IngredientFunction, error)
	GetIngredientTag(ctx context.Context, id int64) (IngredientTag, error)
	GetIngredientTagByName(ctx context.Context, arg GetIngredientTagByNameParams) (IngredientTag, error)
	GetIngredientTagMapByIngredientId(ctx context.Context, ingredientID int64) (IngredientTagMap, error)
	GetIngredientTagMapByIngredientTagId(ctx context.Context, ingredientTagID int64) (IngredientTagMap, error)
	GetInventoryItem(ctx context.Context, id int64) (InventoryItem, error)
	GetLatestVersion(ctx context.Context) (Version, error)
	GetPhase(ctx context.Context, id int64) (Phase, error)
	GetPhasesNotInUpdate(ctx context.Context, arg GetPhasesNotInUpdateParams) ([]Phase, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetStripeByUserId(ctx context.Context, userID int64) (Stripe, error)
	GetStripePlanByUserAccess(ctx context.Context, userAccessID int32) (StripePlan, error)
	GetTagMap(ctx context.Context, arg GetTagMapParams) (IngredientTagMap, error)
	GetTesterByEmail(ctx context.Context, email string) (Tester, error)
	GetTransfer(ctx context.Context, id int64) (Transfer, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByUserEmail(ctx context.Context, email string) (User, error)
	GetUserByUserName(ctx context.Context, userName string) (User, error)
	ListBatchItemsByUserId(ctx context.Context, batchID int64) ([]BatchItem, error)
	ListBatchesByUserId(ctx context.Context, arg ListBatchesByUserIdParams) ([]Batch, error)
	ListCurrencies(ctx context.Context, arg ListCurrenciesParams) ([]Currency, error)
	ListFormulaIngredientsByPhaseId(ctx context.Context, phaseID int64) ([]FormulaIngredient, error)
	ListFormulasByUserId(ctx context.Context, arg ListFormulasByUserIdParams) ([]Formula, error)
	ListIngredientFunctionsByUserId(ctx context.Context, arg ListIngredientFunctionsByUserIdParams) ([]IngredientFunction, error)
	ListIngredientTags(ctx context.Context, userID int64) ([]IngredientTag, error)
	ListIngredientTagsByIngredientId(ctx context.Context, id int64) ([]ListIngredientTagsByIngredientIdRow, error)
	ListIngredients(ctx context.Context, arg ListIngredientsParams) ([]Ingredient, error)
	ListIngredientsByUserId(ctx context.Context, arg ListIngredientsByUserIdParams) ([]Ingredient, error)
	ListInventoryItemsByUserId(ctx context.Context, arg ListInventoryItemsByUserIdParams) ([]InventoryItem, error)
	ListPhasesByFormulaId(ctx context.Context, formulaID int64) ([]Phase, error)
	ListStripePlans(ctx context.Context, arg ListStripePlansParams) ([]StripePlan, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateBatch(ctx context.Context, arg UpdateBatchParams) (Batch, error)
	UpdateBatchItem(ctx context.Context, arg UpdateBatchItemParams) (BatchItem, error)
	UpdateCurrency(ctx context.Context, id int64) (Currency, error)
	UpdateFormula(ctx context.Context, arg UpdateFormulaParams) (Formula, error)
	UpdateFormulaIngredient(ctx context.Context, arg UpdateFormulaIngredientParams) (FormulaIngredient, error)
	UpdateIngredient(ctx context.Context, arg UpdateIngredientParams) (Ingredient, error)
	UpdateIngredientFunction(ctx context.Context, arg UpdateIngredientFunctionParams) (IngredientFunction, error)
	UpdateIngredientTag(ctx context.Context, id int64) (IngredientTag, error)
	UpdateIngredientTagMap(ctx context.Context, arg UpdateIngredientTagMapParams) (IngredientTagMap, error)
	UpdateInventoryItem(ctx context.Context, arg UpdateInventoryItemParams) (InventoryItem, error)
	UpdatePhase(ctx context.Context, arg UpdatePhaseParams) (Phase, error)
	UpdateStripeByUserId(ctx context.Context, arg UpdateStripeByUserIdParams) (Stripe, error)
	UpdateTester(ctx context.Context, arg UpdateTesterParams) (Tester, error)
	UpdateUserHash(ctx context.Context, arg UpdateUserHashParams) (User, error)
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (User, error)
}

var _ Querier = (*Queries)(nil)
