// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: user.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
                   full_name,
                   hash,
                   user_name,
                   email
) VALUES (
  $1, $2, $3, $4
) RETURNING id, user_name, email, full_name, hash, created_at
`

type CreateUserParams struct {
	FullName string `json:"fullName"`
	Hash     string `json:"hash"`
	UserName string `json:"userName"`
	Email    string `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.FullName,
		arg.Hash,
		arg.UserName,
		arg.Email,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.Email,
		&i.FullName,
		&i.Hash,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, user_name, email, full_name, hash, created_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.Email,
		&i.FullName,
		&i.Hash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUserEmail = `-- name: GetUserByUserEmail :one
SELECT id, user_name, email, full_name, hash, created_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByUserEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUserEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.Email,
		&i.FullName,
		&i.Hash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUserName = `-- name: GetUserByUserName :one
SELECT id, user_name, email, full_name, hash, created_at FROM users
WHERE user_name = $1 LIMIT 1
`

func (q *Queries) GetUserByUserName(ctx context.Context, userName string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUserName, userName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.Email,
		&i.FullName,
		&i.Hash,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, user_name, email, full_name, hash, created_at FROM users
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.UserName,
			&i.Email,
			&i.FullName,
			&i.Hash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserHash = `-- name: UpdateUserHash :one
UPDATE users
SET hash = $2
WHERE id = $1
RETURNING id, user_name, email, full_name, hash, created_at
`

type UpdateUserHashParams struct {
	ID   int64  `json:"id"`
	Hash string `json:"hash"`
}

func (q *Queries) UpdateUserHash(ctx context.Context, arg UpdateUserHashParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserHash, arg.ID, arg.Hash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.Email,
		&i.FullName,
		&i.Hash,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserName = `-- name: UpdateUserName :one
UPDATE users
SET full_name = $2
WHERE id = $1
RETURNING id, user_name, email, full_name, hash, created_at
`

type UpdateUserNameParams struct {
	ID       int64  `json:"id"`
	FullName string `json:"fullName"`
}

func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserName, arg.ID, arg.FullName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.Email,
		&i.FullName,
		&i.Hash,
		&i.CreatedAt,
	)
	return i, err
}
