apiVersion: apps/v1
kind: Deployment
metadata:
  name: formulating-api-deployment
  labels:
    app: formulating-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: formulating-api
  template:
    metadata:
      labels:
        app: formulating-api
    spec:
      containers:
        - name: formulating-api
          image: 862881304980.dkr.ecr.eu-north-1.amazonaws.com/formulating:d6ea05cccb3b52b4339108cc3077adb7b459362b
          ports:
            - containerPort: 8080