apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: nginx
spec:
  controller: k8s.io/ingress-nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: formulating-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: "api.kerok.se"
    http:
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: formulating-api-service
              port:
                number: 80